import { Medicine } from "@/types";

export const MOCK_MEDICINES: Medicine[] = [
    {
        id: "1",
        name: "Amoxicillin 500mg",
        brand: "GlaxoSmithKline",
        category: "Antibiotics",
        price: 12.50,
        description: "Broad-spectrum antibiotic used to treat various bacterial infections.",
        rating: 4.8,
        stock: 50,
        requiresPrescription: true,
    },
    {
        id: "2",
        name: "Paracetamol Extra",
        brand: "Panadol",
        category: "Pain Relief",
        price: 5.99,
        description: "Relief from headache, migraine, backache, toothache and rheumatic pain.",
        rating: 4.9,
        stock: 100,
        requiresPrescription: false,
    },
    {
        id: "3",
        name: "Vitamin D3 2000IU",
        brand: "Nature Made",
        category: "Wellness",
        price: 18.25,
        description: "High-potency vitamin D supplement for bone and immune support.",
        rating: 4.7,
        stock: 75,
        requiresPrescription: false,
    },
    {
        id: "4",
        name: "Metformin 500mg",
        brand: "Glucophage",
        category: "Diabetes",
        price: 15.75,
        description: "Medication used to treat type 2 diabetes by controlling blood sugar levels.",
        rating: 4.8,
        stock: 60,
        requiresPrescription: true,
    },
    {
        id: "5",
        name: "Cetirizine 10mg",
        brand: "Zyrtec",
        category: "Allergy",
        price: 9.99,
        description: "Non-drowsy antihistamine for relief of hay fever and allergy symptoms.",
        rating: 4.6,
        stock: 120,
        requiresPrescription: false,
    }
];
